### ISSUE TITLE
So... are you really letting anyone copy the StS jar file? .-.

### ISSUE THREAD

**Issue by Clauvin** [bennyrich/StSFFTCharMod#1]
Going straight to the point: whoever would want to mod the game would at least have bought the game or played it somehow, and even if they didn't, letting anyone download the .jar, which alone is the whole game, without permission of Mega Crit, is piracy.

Nothing against the mod, but can you remove that link of your README and the .jar of that link?

Thanks, and also A FFT CHAR MOD, .O. Go for it :D

**Comment by erasels** [comment]
Free StS PogChamp

**Comment by bennyrich** [comment]
Thank you so much. That was a mistake on my part (miscommunication) and the file and the link have both been removed. Also, thanks for the support :) we're still brainstorming ideas of how to implement the character, whether to do a single character, or one for each job class, or something in between. So feel free to post up any suggestions you might have.
